export const PLACEHOLDERS = new Set(['various', 'misc', 'unknown', 'none', '']);

export const CHARACTERS_BY_GAME = {
  nadia: [
    'Alia', 'Clare', 'Diana', 'Emily', 'Evie', 'Janet', 'Jessica',
    'Kaley', 'Madalyn', 'Naomi', 'Pricia', 'Sofia', 'Tasha', 'Amber', 'Valerie', 'Katherine',
  ],
  genesis: [
    'Andrea', 'Arianna', 'Carol', 'Casandra', 'Chloe', 'Debra', 'Diana',
    'Ella', 'Erica', 'Hannah', 'Heather', 'Judy', 'Kimberly', 'Lillian',
    'Lisa', 'Madalyn', 'Melissa', 'Nellie', 'Oracle', 'Tara',
    'Alia', 'Amber', 'Bancroft', 'Clare', 'Evie', 'Janet', 'Jessica',
    'Kaley', 'Katherine', 'Naomi', 'Sofia', 'Valerie', 'William',
  ],
  symphony: [
    'Agrat', 'Amira', 'Anya', 'Athena', 'Autumn', 'Cleopatra', 'Divya',
    'Empusa', 'Grace', 'Julia', 'Kelli', 'Leila', 'Lola', 'Lucy',
    'Madison', 'Margaret', 'Medusa', 'Nia', 'Nora', 'Olivia', 'Sofia',
    'Carol', 'Naomi', 'Melissa', 'Evie', 'Lillian', 'Ella', 'Clare',
  ],
};

export const GAME_VALID_CHARACTERS = {
  nadia: new Set([
    'Alia', 'Clare', 'Diana', 'Emily', 'Evie', 'Janet', 'Jessica',
    'Kaley', 'Madalyn', 'Naomi', 'Pricia', 'Sofia', 'Tasha',
    'Amber', 'Valerie', 'Katherine',
  ]),
  genesis: new Set([
    'Andrea', 'Arianna', 'Carol', 'Casandra', 'Chloe', 'Debra', 'Diana',
    'Ella', 'Erica', 'Hannah', 'Heather', 'Judy', 'Kimberly', 'Lillian',
    'Lisa', 'Madalyn', 'Melissa', 'Nellie', 'Oracle', 'Tara',
    'Alia', 'Amber', 'Bancroft', 'Clare', 'Evie', 'Janet', 'Jessica',
    'Kaley', 'Katherine', 'Naomi', 'Sofia', 'Valerie', 'William',
  ]),
  symphony: new Set([
    'Agrat', 'Amira', 'Anya', 'Athena', 'Autumn', 'Cleopatra', 'Divya',
    'Empusa', 'Grace', 'Julia', 'Kelli', 'Leila', 'Lola', 'Lucy',
    'Madison', 'Margaret', 'Medusa', 'Nia', 'Nora', 'Olivia', 'Sofia',
    'Carol', 'Naomi', 'Melissa', 'Evie', 'Lillian', 'Ella', 'Clare',
  ]),
};

export const GAME_CHARACTER_ALIASES = {
  nadia: {
    al: 'Alia', alia: 'Alia',
    cl: 'Clare', cr: 'Clare', clare: 'Clare',
    di: 'Diana', diana: 'Diana',
    em: 'Emily', emily: 'Emily',
    ev: 'Evie', evie: 'Evie',
    ja: 'Janet', janet: 'Janet',
    je: 'Jessica', jes: 'Jessica', jessica: 'Jessica',
    ka: 'Kaley', kaley: 'Kaley',
    ma: 'Madalyn', md: 'Madalyn', ml: 'Madalyn', maddy: 'Madalyn', madalyn: 'Madalyn',
    na: 'Naomi', naomi: 'Naomi',
    pr: 'Pricia', pricia: 'Pricia',
    so: 'Sofia', sf: 'Sofia', sofia: 'Sofia',
    ta: 'Tasha', tasha: 'Tasha',
    amber: 'Amber',
    va: 'Valerie', valerie: 'Valerie',
    katherine: 'Katherine',
  },
  genesis: {
    ad: 'Andrea', andrea: 'Andrea',
    ar: 'Arianna', arianna: 'Arianna',
    ca: 'Carol', carol: 'Carol',
    ba: 'Casandra', casandra: 'Casandra',
    ch: 'Chloe', chloe: 'Chloe',
    deb: 'Debra', debra: 'Debra',
    di: 'Diana', diana: 'Diana',
    el: 'Ella', ella: 'Ella',
    er: 'Erica', erica: 'Erica',
    ha: 'Hannah', hn: 'Hannah', hannah: 'Hannah',
    he: 'Heather', heather: 'Heather',
    ju: 'Judy', judy: 'Judy',
    ki: 'Kimberly', km: 'Kimberly', kimberly: 'Kimberly',
    li: 'Lillian', lillian: 'Lillian',
    lisa: 'Lisa',
    ma: 'Madalyn', md: 'Madalyn', madalyn: 'Madalyn',
    me: 'Melissa', mel: 'Melissa', melissa: 'Melissa',
    ne: 'Nellie', nellie: 'Nellie', no: 'Nellie',
    oracle: 'Oracle',
    tara: 'Tara',
    wi: 'William', william: 'William',
    al: 'Alia', alia: 'Alia',
    amber: 'Amber',
    banc: 'Bancroft', bancroft: 'Bancroft',
    cl: 'Clare', cr: 'Clare', clare: 'Clare',
    ev: 'Evie', evie: 'Evie',
    ja: 'Janet', janet: 'Janet',
    je: 'Jessica', jes: 'Jessica', jessica: 'Jessica',
    ka: 'Kaley', kaley: 'Kaley',
    kata: 'Katherine', katherine: 'Katherine',
    na: 'Naomi', naomi: 'Naomi',
    so: 'Sofia', sf: 'Sofia', sofia: 'Sofia',
    val: 'Valerie', valerie: 'Valerie',
  },
  symphony: {
    ag: 'Agrat', agrat: 'Agrat',
    am: 'Amira', amira: 'Amira',
    ay: 'Anya', anya: 'Anya',
    at: 'Athena', athena: 'Athena',
    au: 'Autumn', autumn: 'Autumn',
    cp: 'Cleopatra', cleo: 'Cleopatra', cleopatra: 'Cleopatra',
    di: 'Divya', divya: 'Divya',
    em: 'Empusa', empusa: 'Empusa',
    gr: 'Grace', grace: 'Grace',
    ju: 'Julia', julia: 'Julia',
    ke: 'Kelli', kelli: 'Kelli',
    le: 'Leila', leila: 'Leila',
    lo: 'Lola', lola: 'Lola',
    lu: 'Lucy', lucy: 'Lucy',
    ma: 'Madison', madison: 'Madison',
    mg: 'Margaret', margaret: 'Margaret',
    md: 'Medusa', medusa: 'Medusa',
    ni: 'Nia', nia: 'Nia',
    no: 'Nora', nora: 'Nora',
    ol: 'Olivia', olivia: 'Olivia',
    so: 'Sofia', sf: 'Sofia', sofia: 'Sofia',
    ca: 'Carol', carol: 'Carol',
    na: 'Naomi', naomi: 'Naomi',
    me: 'Melissa', mel: 'Melissa', melissa: 'Melissa',
    ev: 'Evie', evie: 'Evie',
    li: 'Lillian', lillian: 'Lillian',
    el: 'Ella', ella: 'Ella',
    cl: 'Clare', cr: 'Clare', clare: 'Clare',
  },
};

export const CHARACTER_ALIASES = {
  al: 'Alia', alia: 'Alia',
  cl: 'Clare', cr: 'Clare', clare: 'Clare',
  di: 'Diana', diana: 'Diana',
  em: 'Emily', emily: 'Emily',
  ev: 'Evie', evie: 'Evie',
  ja: 'Janet', janet: 'Janet',
  je: 'Jessica', jes: 'Jessica', jessica: 'Jessica',
  ka: 'Kaley', kaley: 'Kaley',
  ma: 'Madalyn', md: 'Madalyn', ml: 'Madalyn', maddy: 'Madalyn', madalyn: 'Madalyn',
  na: 'Naomi', naomi: 'Naomi',
  pr: 'Pricia', pricia: 'Pricia',
  so: 'Sofia', sf: 'Sofia', sofia: 'Sofia',
  ta: 'Tasha', tasha: 'Tasha',
  amber: 'Amber',
  va: 'Valerie', valerie: 'Valerie',
  katherine: 'Katherine', kata: 'Katherine',
  he: 'Heather', heather: 'Heather',
  ki: 'Kimberly', km: 'Kimberly', kimberly: 'Kimberly',
  ca: 'Carol', carol: 'Carol',
  ch: 'Chloe', chloe: 'Chloe',
  ju: 'Judy', judy: 'Judy',
  li: 'Lillian', lillian: 'Lillian',
  er: 'Erica', erica: 'Erica',
  el: 'Ella', ella: 'Ella',
  ne: 'Nellie', nellie: 'Nellie',
  ad: 'Andrea', andrea: 'Andrea',
  me: 'Melissa', mel: 'Melissa', melissa: 'Melissa',
  ha: 'Hannah', hn: 'Hannah', hannah: 'Hannah',
  ar: 'Arianna', arianna: 'Arianna',
  ba: 'Casandra', casandra: 'Casandra',
  deb: 'Debra', debra: 'Debra',
  lisa: 'Lisa',
  oracle: 'Oracle',
  wi: 'William', william: 'William',
  banc: 'Bancroft', bancroft: 'Bancroft',
  ag: 'Agrat', agrat: 'Agrat',
  am: 'Amira', amira: 'Amira',
  ay: 'Anya', anya: 'Anya',
  at: 'Athena', athena: 'Athena',
  au: 'Autumn', autumn: 'Autumn',
  cp: 'Cleopatra', cleo: 'Cleopatra', cleopatra: 'Cleopatra',
  divya: 'Divya',
  empusa: 'Empusa',
  gr: 'Grace', grace: 'Grace',
  julia: 'Julia',
  ke: 'Kelli', kelli: 'Kelli',
  le: 'Leila', leila: 'Leila',
  lo: 'Lola', lola: 'Lola',
  lu: 'Lucy', lucy: 'Lucy',
  madison: 'Madison',
  mg: 'Margaret', margaret: 'Margaret',
  medusa: 'Medusa',
  ni: 'Nia', nia: 'Nia',
  no: 'Nora', nora: 'Nora',
  ol: 'Olivia', olivia: 'Olivia',
};

export const GAME_SPECIFIC_CHARACTERS = {
  symphony: {
    ju: 'Julia',
    di: 'Divya',
    divya: 'Divya',
    em: 'Empusa',
    empusa: 'Empusa',
    md: 'Medusa',
    me: 'Medusa',
    medusa: 'Medusa',
    ma: 'Madison',
    madison: 'Madison',
    cl: 'Cleopatra',
    cp: 'Cleopatra',
    cleo: 'Cleopatra',
    cleopatra: 'Cleopatra',
    au: 'Autumn',
    autumn: 'Autumn',
    ke: 'Kelli',
    kelli: 'Kelli',
    lu: 'Lucy',
    lucy: 'Lucy',
    no: 'Nora',
    nora: 'Nora',
  },
  nadia: {
    ju: 'Judy',
    di: 'Diana',
    em: 'Emily',
    md: 'Madalyn',
    ma: 'Madalyn',
    ml: 'Madalyn',
    cl: 'Clare',
  },
  genesis: {
    ju: 'Judy',
    di: 'Diana',
    md: 'Madalyn',
    me: 'Melissa',
    ma: 'Madalyn',
    no: 'Nellie',
  },
};

export const HEROINE_2LETTER_CODES = new Set(
  Object.values(GAME_CHARACTER_ALIASES).flatMap((gameDict) =>
    Object.entries(gameDict)
      .filter(([alias, canonical]) => alias.length === 2 && canonical !== 'William')
      .map(([alias]) => alias.toLowerCase())
  )
);

export function isHeroineCode(code, game = '') {
  if (!code) return false;
  const lower = String(code).toLowerCase();
  if (lower.length !== 2) return false;
  if (game && GAME_CHARACTER_ALIASES[game]) {
    const canonical = GAME_CHARACTER_ALIASES[game][lower];
    return Boolean(canonical && canonical !== 'William');
  }
  return HEROINE_2LETTER_CODES.has(lower);
}
